# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Standard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Resolver'
  
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Functions'
  pod 'Stripe'


  # Pods for Standard

  target 'StandardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StandardUITests' do
    # Pods for testing
  end

end
m
