# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'standard-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Stripe'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'web3.swift'

  target 'standard-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'standard-iosUITests' do
    # Pods for testing
  end

end
